version: '3'

services:
    nginx-delivery:
        container_name: nginx-delivery
        image: nginx:1.24.0
        restart: "no"
        ports:
            - "8081:80"
        volumes:
            - .:/var/www/
            # конфигурация nginx
            - ./.docker/config/nginx/:/etc/nginx/conf.d/
            # логи
            - ./.docker/logs/nginx:/var/log/nginx/
        networks:
            - web-network-delivery

    php-delivery:
        build:
            context: ./.docker/
        container_name: php-delivery
        restart: "no"
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www/
        networks:
            - web-network-delivery

    mysql-delivery:
        container_name: mysql-delivery
        image: mariadb:11.1.2
        restart: "no"
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./logs/mysql/:/var/logs/mysql
            - db-mysql:/var/lib/mysql
        security_opt:
            - seccomp:unconfined
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - web-network-delivery

    redis-delivery:
        container_name: redis-delivery
        image: redis:7.2.1
        restart: "no"
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - db-redis:/data
        networks:
            - web-network-delivery

volumes:
    db-mysql:
    db-redis:

networks:
    web-network-delivery:
        driver: bridge
